### PR TITLE
WIP: fix optional keyword typo

### LINKED ISSUE #13: In data type definitions page, there are `+optional` keywords in field's description
http://www.kubevirt.io/api-reference/master/definitions.html
domain-spec-screenshot

### PR DESCRIPTION
**Pull request by MalloZup**
Fix #13

### CODE REVIEW

**Comment by MalloZup** [comment]
i think this doc is autogenerated so  i will look on the other repo also

**Comment by fabiand** [comment]
Yes, it's auto generated from annotations in https://github.com/kubevirt/kubevirt

A typo is good because you can probably quickly grep it ;)

**Comment by fabiand** [comment]
Let me know if you need some help

**Comment by MalloZup** [comment]
yop thx @fabiand  i think is a good entry-point to learn the openapi-spec. I don't think i would need help for this small task, is just about start reading and learning in pragmatic ways :robot:  :radio: :bookmark: :sun_with_face:

**Comment by fabiand** [comment]
So many nice emojis!

:tada:

Good luck then :+1: :)

**Comment by MalloZup** [comment]
ciao @fabiand, one question since i where around on this issue and i investigate a little.

I discovered the open-api and found out you use this tool for generating the doc. ( never heard about before :smile: )
https://github.com/kubevirt/kubevirt/tree/bf3b2e02837ece11d7ad2666d67033649456f2e7/hack/gen-swagger-doc

I will try this out, but i think we might add in this repo README.md about how to generate the doc, once i will have time to experiment about it ( adding in my todo list)

From curiosity pov, why was choosed the swagger.java client and not something not in golang?
https://github.com/go-swagger/go-swagger, like this one. I am pretty unexpert atm so i just ask blindly :dog:

**Comment by fabiand** [comment]
Yo!

java is only needed to generate the swagger documentaion (not the openapi spec), and maybe there is just no golang tool available generatig swagger docs.

**Comment by lukas-bednar** [comment]
@MalloZup Hi, it would be great if you added readme into this directory !!
Regarding generation itself, we have a target in Makefile for that `apidocs`, there you can follow what are steps to generate it.

**Comment by rmohr** [comment]
@MalloZup the background is that our golang swagger-generator does not recognize `+optional` as something special. We may be able to switch to https://github.com/kubernetes/code-generator/tree/master/cmd/openapi-gen. If not, we would have to teach https://github.com/rmohr/go-swagger-utils to interpret +optional.

**Comment by rmohr** [comment]
Ok, so we can switch. The steps on how to do this are outlined in https://github.com/kubevirt/kubevirt/issues/1227

**Pull request closed without merging**
